ServerEvents.tags("item", event => {
    /*——————真菌生物掉落——————*/
    //t1掉落物
    event.add('katabasis:spore_tissue_t1', 'spore:mutated_fiber')
    event.add('katabasis:spore_tissue_t1', 'spore:mutated_heart')
    //t2掉落物
    event.add('katabasis:spore_tissue_t2', 'spore:cerebrum')
    event.add('katabasis:spore_tissue_t2', 'spore:spine_fragment')
    //t3掉落物(通用)
    event.add('katabasis:spore_tissue_t3', 'spore:organoid_membrane')
    event.add('katabasis:spore_tissue_t3', 'spore:armor_fragment')
    event.add('katabasis:spore_tissue_t3', 'spore:claw_fragment')
    event.add('katabasis:spore_tissue_t3', 'spore:innards')
    event.add('katabasis:spore_tissue_t3', 'spore:tendons')
    event.add('katabasis:spore_tissue_t3', 'spore:tumor')
    event.add('katabasis:spore_tissue_t3', 'spore:alveolic_sack')
    event.add('katabasis:spore_tissue_t3', 'spore:fang')
    event.add('katabasis:spore_tissue_t3', 'spore:sickle_fragment')
    event.add('katabasis:spore_tissue_t3', 'spore:shield_fragment')
    event.add('katabasis:spore_tissue_t3', 'spore:wing_membrane')
    event.add('katabasis:spore_tissue_t3', 'spore:spine')
    event.add('katabasis:spore_tissue_t3', 'spore:spike')
    event.add('katabasis:spore_tissue_t3', 'spore:altered_spleen')
    event.add('katabasis:spore_tissue_t3', 'spore:corrosive_sack')

    //机素动能配件
    event.add('katabasis:firearm_accessories', 'pointblank:absorber')
    event.add('katabasis:firearm_accessories', 'pointblank:assaultgrip')
    event.add('katabasis:firearm_accessories', 'pointblank:assaultgripii')
    event.add('katabasis:firearm_accessories', 'pointblank:basicsight')
    event.add('katabasis:firearm_accessories', 'pointblank:calibrator')
    event.add('katabasis:firearm_accessories', 'pointblank:crossnozzle_barrel')
    event.add('katabasis:firearm_accessories', 'pointblank:crystalreflector')
    event.add('katabasis:firearm_accessories', 'pointblank:doublecrystalreflector')
    event.add('katabasis:firearm_accessories', 'pointblank:highpressuresuppressor')
    event.add('katabasis:firearm_accessories', 'pointblank:highpressuresuppressorii')
    event.add('katabasis:firearm_accessories', 'pointblank:horizon')
    event.add('katabasis:firearm_accessories', 'pointblank:horizon_vol')
    event.add('katabasis:firearm_accessories', 'pointblank:polareye400')
    event.add('katabasis:firearm_accessories', 'pointblank:polareye600')
    event.add('katabasis:firearm_accessories', 'pointblank:polareye800')
    event.add('katabasis:firearm_accessories', 'pointblank:pressureaccelerator')
    event.add('katabasis:firearm_accessories', 'pointblank:sentinelgrip')
    event.add('katabasis:firearm_accessories', 'pointblank:sentinelgripii')
    event.add('katabasis:firearm_accessories', 'pointblank:sentinelgripiii')
    event.add('katabasis:firearm_accessories', 'pointblank:tanksuppressor')
    event.add('katabasis:firearm_accessories', 'pointblank:turbulencesuppressor')
})